# Generated by Django 3.0.7 on 2020-06-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='gaurav/images/blogimages'),
        ),
    ]
